[workspace]
name = "shennong-tangram"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = "==3.11.16"
scanpy = "==1.11.5"
anndata = "==0.12.19"
pandas = "==2.3.3"
scipy = "==1.17.1"
numpy = "==1.26.4"

[pypi-dependencies]
tangram-sc = "==1.0.4"

[feature.cpu]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[feature.cpu.dependencies]
pytorch-cpu = "==2.5.1"

[feature.gpu]
platforms = ["linux-64"]

[feature.gpu.system-requirements]
cuda = "{{ cuda_major }}"

[feature.gpu.dependencies]
pytorch-gpu = "==2.5.1"
cuda-version = "=={{ cuda_version }}"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
default = ["cpu"]
