[workspace]
name = "shennong-cellphonedb"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = "==3.11.16"
pandas = "==2.3.3"
numpy = "==1.26.4"
scipy = "==1.13.1"
pip = "==25.3"

[pypi-dependencies]
cellphonedb = "==5.0.1"

[environments]
default = []
