[workspace]
name = "shennong-cellphonedb"
channels = ["conda-forge"]
platforms = ["{{ platform }}"]

[dependencies]
python = ">=3.10,<3.12"
pandas = ">=2"
numpy = "*"
scipy = "*"
pip = "*"

[pypi-dependencies]
cellphonedb = "==5.0.1"
autozyme = { git = "https://github.com/zerostwo/autozyme.git", rev = "8fc2e9c3a7f70302f97589aaa9b0395dcf86f9bc", subdirectory = "autozyme_py" }

[environments]
default = []
