[workspace]
name = "shennong-squidpy"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = "==3.11.16"
scanpy = "==1.11.5"
squidpy = "==1.8.2"
anndata = "==0.12.19"
pandas = "==2.3.3"
scipy = "==1.17.1"
numpy = "==2.4.6"

[environments]
default = []
