[workspace]
name = "shennong-stlearn"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = "==3.12.14"
scanpy = "==1.12.4"
anndata = "==0.12.19"
pandas = "==2.3.3"
scipy = "==1.17.1"
numpy = "==2.4.6"
pip = "==25.3"

[pypi-dependencies]
stlearn = "==1.4.1"

[environments]
default = []
