---
title: "clustering"
author: 
- name: Songqi Duan
  email: duan@songqi.org
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{clustering}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
run_vignette <- identical(Sys.getenv("SHENNONG_RUN_VIGNETTES"), "true")
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 8,
  fig.height = 6,
  eval = run_vignette
)
```

This vignette documents the clustering workflow used in the package. To keep
package checks fast and deterministic, the code chunks are shown but not
evaluated unless `SHENNONG_RUN_VIGNETTES=true` is set in the environment.

```{r setup}
library(Shennong)
library(Seurat)
```

```{r}
filtered_path <- sn_load_data(
  dataset = "pbmc3k",
  matrix_type = "filtered",
  return_object = FALSE
)

raw_path <- sn_load_data(
  dataset = "pbmc3k",
  matrix_type = "raw",
  return_object = FALSE
)
```

```{r}
ambient_counts <- sn_remove_ambient_contamination(
  x = filtered_path,
  raw = raw_path,
  method = "soupx",
  return_object = FALSE
)
```

```{r}
seurat_obj <- sn_initialize_seurat_object(x = ambient_counts, species = "human")
```

```{r}
seurat_obj <- sn_filter_cells(seurat_obj, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"))
```

```{r}
seurat_obj <- sn_filter_genes(seurat_obj)
```

```{r}
seurat_obj <- sn_run_cluster(object = seurat_obj, resolution = 1)
```

```{r}
DimPlot(seurat_obj, group.by = "seurat_clusters", label = TRUE) + NoLegend()
```

```{r}
sessioninfo::session_info()
```
