[workspace]
name = "shennong-popv"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = "==3.11.16"
pytorch-cpu = "==2.5.1"
numpy = "==1.26.4"
pandas = "==2.3.3"
scipy = "==1.17.1"
anndata = "==0.12.19"
scanpy = "==1.11.5"
scikit-learn = "==1.7.2"

[pypi-dependencies]
popv = "==0.6.1"

[environments]
default = []
