// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// soupx_expand_corrected_x_cpp
NumericVector soupx_expand_corrected_x_cpp(IntegerVector p, IntegerVector row_i, NumericVector x, NumericMatrix n_soup, IntegerVector cluster_id, NumericVector cell_weights);
RcppExport SEXP _Shennong_soupx_expand_corrected_x_cpp(SEXP pSEXP, SEXP row_iSEXP, SEXP xSEXP, SEXP n_soupSEXP, SEXP cluster_idSEXP, SEXP cell_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type row_i(row_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type n_soup(n_soupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster_id(cluster_idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell_weights(cell_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(soupx_expand_corrected_x_cpp(p, row_i, x, n_soup, cluster_id, cell_weights));
    return rcpp_result_gen;
END_RCPP
}
// soupx_cluster_soup_from_cells_cpp
NumericMatrix soupx_cluster_soup_from_cells_cpp(IntegerVector p, IntegerVector row_i, NumericVector x, IntegerVector cluster_id, NumericVector cell_targets, NumericVector soup_frac, int n_genes, int n_clusters);
RcppExport SEXP _Shennong_soupx_cluster_soup_from_cells_cpp(SEXP pSEXP, SEXP row_iSEXP, SEXP xSEXP, SEXP cluster_idSEXP, SEXP cell_targetsSEXP, SEXP soup_fracSEXP, SEXP n_genesSEXP, SEXP n_clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type row_i(row_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster_id(cluster_idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell_targets(cell_targetsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type soup_frac(soup_fracSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< int >::type n_clusters(n_clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(soupx_cluster_soup_from_cells_cpp(p, row_i, x, cluster_id, cell_targets, soup_frac, n_genes, n_clusters));
    return rcpp_result_gen;
END_RCPP
}
// soupx_adjust_counts_no_cluster_x_cpp
NumericVector soupx_adjust_counts_no_cluster_x_cpp(IntegerVector p, IntegerVector row_i, NumericVector x, NumericVector cell_targets, NumericVector soup_frac, int n_genes);
RcppExport SEXP _Shennong_soupx_adjust_counts_no_cluster_x_cpp(SEXP pSEXP, SEXP row_iSEXP, SEXP xSEXP, SEXP cell_targetsSEXP, SEXP soup_fracSEXP, SEXP n_genesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type row_i(row_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell_targets(cell_targetsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type soup_frac(soup_fracSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    rcpp_result_gen = Rcpp::wrap(soupx_adjust_counts_no_cluster_x_cpp(p, row_i, x, cell_targets, soup_frac, n_genes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Shennong_soupx_expand_corrected_x_cpp", (DL_FUNC) &_Shennong_soupx_expand_corrected_x_cpp, 6},
    {"_Shennong_soupx_cluster_soup_from_cells_cpp", (DL_FUNC) &_Shennong_soupx_cluster_soup_from_cells_cpp, 8},
    {"_Shennong_soupx_adjust_counts_no_cluster_x_cpp", (DL_FUNC) &_Shennong_soupx_adjust_counts_no_cluster_x_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_Shennong(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
