# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soupx_expand_corrected_x_cpp <- function(p, row_i, x, n_soup, cluster_id, cell_weights) {
    .Call(`_Shennong_soupx_expand_corrected_x_cpp`, p, row_i, x, n_soup, cluster_id, cell_weights)
}

soupx_cluster_soup_from_cells_cpp <- function(p, row_i, x, cluster_id, cell_targets, soup_frac, n_genes, n_clusters) {
    .Call(`_Shennong_soupx_cluster_soup_from_cells_cpp`, p, row_i, x, cluster_id, cell_targets, soup_frac, n_genes, n_clusters)
}

soupx_adjust_counts_no_cluster_x_cpp <- function(p, row_i, x, cell_targets, soup_frac, n_genes) {
    .Call(`_Shennong_soupx_adjust_counts_no_cluster_x_cpp`, p, row_i, x, cell_targets, soup_frac, n_genes)
}
